// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_AutoRenta.Context;

namespace Proyecto_AutoRenta.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230726051228_example")]
    partial class example
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.AtenCliente", b =>
                {
                    b.Property<int>("IDTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IDTicket");

                    b.ToTable("AtencionAlCliente");
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Reserve", b =>
                {
                    b.Property<int>("PkReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FkVehiculos")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkReserva");

                    b.HasIndex("FkVehiculos");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Rol", b =>
                {
                    b.Property<int>("PkRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            PkRol = 1,
                            Nombre = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Usuario", b =>
                {
                    b.Property<int>("PkUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FkRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkUsuario");

                    b.HasIndex("FkRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            PkUsuario = 1,
                            FkRol = 1,
                            Nombre = "Jony",
                            Password = "admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Vehiculos", b =>
                {
                    b.Property<int>("PkVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Tarifa")
                        .HasColumnType("double");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkVehiculo");

                    b.ToTable("Vehiculo");

                    b.HasData(
                        new
                        {
                            PkVehiculo = 1,
                            Modelo = "2023223",
                            Tarifa = 123.0,
                            Tipo = "Deportivo"
                        });
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Reserve", b =>
                {
                    b.HasOne("Proyecto_AutoRenta.Entities.Vehiculos", "Vehiculos")
                        .WithMany()
                        .HasForeignKey("FkVehiculos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Usuario", b =>
                {
                    b.HasOne("Proyecto_AutoRenta.Entities.Rol", "Roles")
                        .WithMany()
                        .HasForeignKey("FkRol");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
